# Generated by Django 5.2.5 on 2025-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='raiting',
            field=models.PositiveSmallIntegerField(default='2'),
            preserve_default=False,
        ),
    ]
