# Generated by Django 5.2.5 on 2025-09-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='raiting',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
