# Generated by Django 5.2.5 on 2025-08-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_num', models.IntegerField()),
                ('second_num', models.IntegerField()),
                ('amal', models.IntegerField()),
                ('result', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Calculator',
                'verbose_name_plural': 'Calculators',
            },
        ),
    ]
