# Generated by Django 5.2.5 on 2025-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatormodel',
            name='amal',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='calculatormodel',
            name='result',
            field=models.FloatField(),
        ),
    ]
